//! Byte-for-byte parity between the Rust normalizer and CPython's
//! `json.dumps(obj, sort_keys=True, indent=2, ensure_ascii=False) + "\n"`
//! (the normalizer in `scripts/roundtrip.py`).
//!
//! `fixtures/expected/*` were generated by running `fixtures/generate.py`
//! with CPython (3.9.6 on the dev machine); `fixtures/cases/*` are the raw
//! inputs (deliberately non-canonical where useful). `fixtures/export-a.zip`
//! is a real Penpot 2.16.2 `export-binfile` v3 archive from the M0 spike, and
//! the two pinned hashes below are the values CPython computed for it in the
//! M0 report (`docs/m0/roundtrip-report.md`).

use std::path::{Path, PathBuf};

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures")
}

/// Every case in the corpus must normalize to the exact bytes CPython wrote.
#[test]
fn corpus_matches_python_byte_for_byte() {
    let cases_dir = fixtures().join("cases");
    let expected_dir = fixtures().join("expected");
    let mut names: Vec<String> = std::fs::read_dir(&cases_dir)
        .expect("cases dir")
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".json"))
        .collect();
    names.sort();
    assert!(
        names.len() >= 6,
        "expected the full fixture corpus, found {names:?}"
    );
    for name in &names {
        let input = std::fs::read(cases_dir.join(name)).expect("case readable");
        let expected = std::fs::read(expected_dir.join(name))
            .unwrap_or_else(|_| panic!("missing expected/{name} — run fixtures/generate.py"));
        let actual = sync_core::normalize_json_bytes(&input, Path::new(name))
            .unwrap_or_else(|e| panic!("normalize {name}: {e}"));
        if actual != expected {
            // Locate the first differing byte for a useful failure message.
            let pos = actual
                .iter()
                .zip(expected.iter())
                .position(|(a, b)| a != b)
                .unwrap_or_else(|| actual.len().min(expected.len()));
            let ctx = |bytes: &[u8]| {
                let lo = pos.saturating_sub(60);
                let hi = (pos + 60).min(bytes.len());
                String::from_utf8_lossy(&bytes[lo..hi]).into_owned()
            };
            panic!(
                "{name}: Rust output diverges from Python at byte {pos}\n  rust:   …{}…\n  python: …{}…",
                ctx(&actual),
                ctx(&expected)
            );
        }
    }
    println!("parity OK for {} cases", names.len());
}

/// Normalization must be idempotent: normalizing Python's output changes nothing.
#[test]
fn normalizer_is_idempotent_on_python_output() {
    let expected_dir = fixtures().join("expected");
    for entry in std::fs::read_dir(&expected_dir).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let bytes = std::fs::read(&path).unwrap();
        let renormalized = sync_core::normalize_json_bytes(&bytes, &path).unwrap();
        assert_eq!(renormalized, bytes, "not idempotent on {}", path.display());
    }
}

/// The real M0 export: unzip → normalize → hash must reproduce the exact
/// hashes CPython computed in `docs/m0/roundtrip-report.md`.
#[test]
fn real_export_hashes_match_m0_python_run() {
    const PY_FORMATTING_HASH: &str =
        "09cd02ac3e06b357643e6b553212326f7d05a14b3be2c1ddf25831828cd57e7c";
    const PY_SEMANTIC_HASH: &str =
        "b2124a9b263292b7416d44db6f3c0a11328968917dc29987c1c386a9503d31b0";

    let zip_bytes = std::fs::read(fixtures().join("export-a.zip")).expect("fixture zip");
    let tmp = tempfile::tempdir().unwrap();
    let tree = tmp.path().join("tree");
    sync_core::unzip_to(&zip_bytes, &tree).unwrap();

    let rewritten = sync_core::normalize_tree(&tree).unwrap();
    assert_eq!(rewritten, 6, "the M0 export has 6 JSON entries");

    let files = sync_core::read_tree(&tree).unwrap();
    assert_eq!(
        sync_core::tree_hash(&files),
        PY_FORMATTING_HASH,
        "formatting-tier hash diverges from the Python normalizer"
    );
    assert_eq!(
        sync_core::semantic_tree_hash(&tree).unwrap(),
        PY_SEMANTIC_HASH,
        "semantic (volatile-stripped) hash diverges from the Python normalizer"
    );

    // normalize_tree must be idempotent on a real export too.
    sync_core::normalize_tree(&tree).unwrap();
    assert_eq!(
        sync_core::tree_hash(&sync_core::read_tree(&tree).unwrap()),
        PY_FORMATTING_HASH
    );
}

/// The semantic hash must not change when only createdAt/modifiedAt differ —
/// this is the no-op detector for DB→FS sync (M0's core finding).
#[test]
fn semantic_hash_ignores_volatile_keys_but_sees_real_changes() {
    let zip_bytes = std::fs::read(fixtures().join("export-a.zip")).unwrap();
    let tmp = tempfile::tempdir().unwrap();
    let tree = tmp.path().join("tree");
    sync_core::unzip_to(&zip_bytes, &tree).unwrap();
    let baseline = sync_core::semantic_tree_hash(&tree).unwrap();

    // Find the file-level JSON (files/<fid>.json) and bump its timestamps —
    // exactly what the server does on every import.
    let fid_json = sync_core::read_tree(&tree)
        .unwrap()
        .keys()
        .find(|k| k.starts_with("files/") && k.ends_with(".json") && k.matches('/').count() == 1)
        .unwrap()
        .clone();
    let path = tree.join(&fid_json);
    let mut v: serde_json::Value =
        serde_json::from_slice(&std::fs::read(&path).unwrap()).unwrap();
    v["createdAt"] = serde_json::json!("2031-01-01T00:00:00.000000Z");
    v["modifiedAt"] = serde_json::json!("2031-01-01T00:00:01.000000Z");
    std::fs::write(&path, serde_json::to_vec(&v).unwrap()).unwrap();
    assert_eq!(
        sync_core::semantic_tree_hash(&tree).unwrap(),
        baseline,
        "timestamp churn must be invisible to the ledger hash"
    );

    // A real change (shape name) must be visible.
    v["name"] = serde_json::json!("renamed-by-test");
    std::fs::write(&path, serde_json::to_vec(&v).unwrap()).unwrap();
    assert_ne!(sync_core::semantic_tree_hash(&tree).unwrap(), baseline);
}

/// Binary (non-JSON) files participate raw: any byte flip changes the hash,
/// and normalize_tree never touches them.
#[test]
fn binaries_hashed_raw_and_never_rewritten() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    std::fs::create_dir_all(root.join("objects")).unwrap();
    let blob = vec![0x89u8, 0x50, 0x4e, 0x47, 0x00, 0xff, 0x10, 0x20];
    std::fs::write(root.join("objects/img.png"), &blob).unwrap();
    std::fs::write(root.join("meta.json"), b"{\"a\":\t1}").unwrap();

    let before = sync_core::semantic_tree_hash(root).unwrap();
    let rewritten = sync_core::normalize_tree(root).unwrap();
    assert_eq!(rewritten, 1);
    assert_eq!(
        std::fs::read(root.join("objects/img.png")).unwrap(),
        blob,
        "binaries must pass through untouched"
    );
    assert_eq!(sync_core::semantic_tree_hash(root).unwrap(), before);

    let mut flipped = blob.clone();
    flipped[3] ^= 0x01;
    std::fs::write(root.join("objects/img.png"), &flipped).unwrap();
    assert_ne!(sync_core::semantic_tree_hash(root).unwrap(), before);
}
