//! Deterministic JSON normalization, byte-compatible with the Python
//! normalizer in `scripts/roundtrip.py`:
//!
//! ```python
//! json.dumps(obj, sort_keys=True, indent=2, ensure_ascii=False) + "\n"
//! ```
//!
//! Byte compatibility is proven by the fixture corpus in `fixtures/`
//! (generated by `fixtures/generate.py` with CPython) — see
//! `tests/python_parity.rs`. The tricky part is number formatting; the rules
//! implemented by [`format_f64`] mirror CPython's `float.__repr__`
//! (shortest round-trip digits, fixed notation iff the decimal point lands
//! in `-3..=16`, exponents as `e±NN` with at least two digits).
//!
//! Known divergences from Python (documented spec — Rust behavior wins;
//! none of these occur in real Penpot exports):
//!
//! - Integer literals outside `i64`/`u64` range: Python keeps arbitrary
//!   precision, serde_json parses them as `f64` (lossy).
//! - The literal `-0` (integer): Python emits `0`, serde_json preserves the
//!   sign as `-0.0`.
//! - `NaN` / `Infinity` tokens and overflowing literals like `1e999`:
//!   Python accepts (and emits invalid JSON back); Rust rejects with a parse
//!   error, which is the safer behavior for a sync engine.

use serde_json::Value;
use std::path::Path;

use crate::{Error, Result};

/// Keys rewritten by the Penpot server on every import (M0 finding: the only
/// volatile fields in a binfile-v3 round-trip). Stripped before hashing.
pub const VOLATILE_KEYS: [&str; 2] = ["createdAt", "modifiedAt"];

/// Serialize a JSON value exactly like
/// `json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False)`.
/// (No trailing newline — callers append it, mirroring roundtrip.py.)
pub fn dumps(value: &Value) -> String {
    let mut out = String::new();
    write_value(&mut out, value, 0);
    out
}

/// Normalize one JSON document: parse + re-serialize deterministically with a
/// trailing newline. Returns the exact bytes the Python normalizer produces.
pub fn normalize_json_bytes(input: &[u8], path_for_errors: &Path) -> Result<Vec<u8>> {
    let value: Value = serde_json::from_slice(input).map_err(|e| Error::Json {
        path: path_for_errors.to_path_buf(),
        source: e,
    })?;
    let mut s = dumps(&value);
    s.push('\n');
    Ok(s.into_bytes())
}

/// Rewrite every `*.json` file under `root` in place (sorted keys, 2-space
/// indent, non-ASCII preserved, LF, single trailing newline). Non-JSON files
/// are untouched. Returns the number of files rewritten (idempotent rewrites
/// still count). Fails on the first unparseable JSON file.
pub fn normalize_tree(root: &Path) -> Result<usize> {
    let mut count = 0;
    for path in crate::util::walk_files(root)? {
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let raw = std::fs::read(&path).map_err(|e| Error::io(&path, e))?;
        let normalized = normalize_json_bytes(&raw, &path)?;
        if normalized != raw {
            std::fs::write(&path, &normalized).map_err(|e| Error::io(&path, e))?;
        }
        count += 1;
    }
    Ok(count)
}

fn indent(out: &mut String, level: usize) {
    for _ in 0..level * 2 {
        out.push(' ');
    }
}

fn write_value(out: &mut String, value: &Value, level: usize) {
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(true) => out.push_str("true"),
        Value::Bool(false) => out.push_str("false"),
        Value::Number(n) => write_number(out, n),
        Value::String(s) => write_string(out, s),
        Value::Array(items) => {
            if items.is_empty() {
                out.push_str("[]");
                return;
            }
            out.push('[');
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                out.push('\n');
                indent(out, level + 1);
                write_value(out, item, level + 1);
            }
            out.push('\n');
            indent(out, level);
            out.push(']');
        }
        Value::Object(map) => {
            if map.is_empty() {
                out.push_str("{}");
                return;
            }
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort_unstable(); // UTF-8 byte order == Unicode code point order
            out.push('{');
            for (i, key) in keys.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                out.push('\n');
                indent(out, level + 1);
                write_string(out, key);
                out.push_str(": ");
                write_value(out, &map[key.as_str()], level + 1);
            }
            out.push('\n');
            indent(out, level);
            out.push('}');
        }
    }
}

/// Python `json.dumps(..., ensure_ascii=False)` string escaping: only `"`,
/// `\`, and control chars < 0x20 are escaped (with the five shorthands);
/// everything else — including non-ASCII, U+2028/9 and DEL — is written raw.
fn write_string(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                use std::fmt::Write;
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

fn write_number(out: &mut String, n: &serde_json::Number) {
    // Integers stay integers (Python json keeps int/float distinct; serde_json
    // likewise parses tokens without '.'/'e' as u64/i64).
    if let Some(u) = n.as_u64() {
        out.push_str(&u.to_string());
    } else if let Some(i) = n.as_i64() {
        out.push_str(&i.to_string());
    } else {
        // serde_json Numbers are never NaN/inf.
        out.push_str(&format_f64(n.as_f64().expect("finite f64")));
    }
}

/// Format an `f64` exactly like CPython's `repr(float)` (which is what
/// `json.dumps` uses): shortest round-trip digits; fixed-point notation when
/// the decimal point position `p` (value = 0.digits × 10^p) is in `-3..=16`,
/// otherwise scientific with `e±NN` (exponent zero-padded to two digits).
///
/// Digits come from ryu, NOT `format!("{:e}")`: on exact decimal ties (the
/// double is precisely halfway between two shortest strings, e.g.
/// 791929834541136.25) Rust std rounds half-away-from-zero but CPython's
/// dtoa rounds half-to-even — and ryu agrees with CPython (verified by the
/// 200k-float live fuzz in `tests/live_python_fuzz.rs`).
pub(crate) fn format_f64(v: f64) -> String {
    if v == 0.0 {
        return if v.is_sign_negative() {
            "-0.0".to_owned()
        } else {
            "0.0".to_owned()
        };
    }
    let mut buf = ryu::Buffer::new();
    let (digits, p) = decompose_shortest(buf.format_finite(v.abs()));

    let mut out = String::new();
    if v.is_sign_negative() {
        out.push('-');
    }
    if (-3..=16).contains(&p) {
        if p <= 0 {
            out.push_str("0.");
            for _ in 0..(-p) {
                out.push('0');
            }
            out.push_str(&digits);
        } else if (p as usize) < digits.len() {
            out.push_str(&digits[..p as usize]);
            out.push('.');
            out.push_str(&digits[p as usize..]);
        } else {
            out.push_str(&digits);
            for _ in 0..(p as usize - digits.len()) {
                out.push('0');
            }
            out.push_str(".0");
        }
    } else {
        out.push_str(&digits[..1]);
        if digits.len() > 1 {
            out.push('.');
            out.push_str(&digits[1..]);
        }
        let e = p - 1;
        out.push('e');
        out.push(if e >= 0 { '+' } else { '-' });
        let ea = e.unsigned_abs();
        if ea < 10 {
            out.push('0');
        }
        out.push_str(&ea.to_string());
    }
    out
}

/// Split a ryu "pretty" rendering (`123.456`, `100000.0`, `1e16`, `5e-324`,
/// `0.0001`, …) of a positive finite value into `(significant_digits, p)`
/// where value = 0.digits × 10^p, digits having no leading/trailing zeros.
fn decompose_shortest(s: &str) -> (String, i32) {
    let (num, exp) = match s.split_once(['e', 'E']) {
        Some((mant, exp)) => (mant, exp.parse::<i32>().expect("exponent")),
        None => (s, 0),
    };
    let (int_part, frac_part) = num.split_once('.').unwrap_or((num, ""));
    let mut digits = String::with_capacity(int_part.len() + frac_part.len());
    digits.push_str(int_part);
    digits.push_str(frac_part);
    let mut p = int_part.len() as i32 + exp;
    let leading = digits.len() - digits.trim_start_matches('0').len();
    digits.drain(..leading);
    p -= leading as i32;
    let significant = digits.trim_end_matches('0').len().max(1);
    digits.truncate(significant);
    (digits, p)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    // The `…136.25` literals below are exact doubles written out in full on
    // purpose (they document the decimal-tie case); clippy suggests `…136.3`
    // which parses to the same bits but hides the point of the test.
    #[allow(clippy::excessive_precision)]
    fn float_repr_matches_python() {
        // Every expectation below is literal CPython repr() output.
        let cases: &[(f64, &str)] = &[
            (0.0, "0.0"),
            (-0.0, "-0.0"),
            (1.0, "1.0"),
            (-1.0, "-1.0"),
            (0.5, "0.5"),
            (0.1, "0.1"),
            (2.0 / 3.0, "0.6666666666666666"),
            (0.1 + 0.2, "0.30000000000000004"),
            (100000.0, "100000.0"),
            (123.456, "123.456"),
            (1e15, "1000000000000000.0"),
            (1e16, "1e+16"),
            (1.5e16, "1.5e+16"),
            (9.007199254740992e15, "9007199254740992.0"),
            (1e-4, "0.0001"),
            (1e-5, "1e-05"),
            (-1e-5, "-1e-05"),
            (1.5e300, "1.5e+300"),
            (5e-324, "5e-324"),
            (f64::MAX, "1.7976931348623157e+308"),
            (f64::MIN_POSITIVE, "2.2250738585072014e-308"),
            (std::f64::consts::PI, "3.141592653589793"),
            // Exact decimal ties: CPython rounds half-to-even (…6.2), while
            // Rust std's `{:e}` would round half-away-from-zero (…6.3).
            (791929834541136.25, "791929834541136.2"),
            (-791929834541136.25, "-791929834541136.2"),
        ];
        for (v, expected) in cases {
            assert_eq!(&format_f64(*v), expected, "for {v:?}");
        }
    }

    #[test]
    fn integers_stay_integers() {
        assert_eq!(dumps(&json!(5)), "5");
        assert_eq!(dumps(&json!(-5)), "-5");
        assert_eq!(dumps(&json!(0)), "0");
        assert_eq!(dumps(&json!(u64::MAX)), "18446744073709551615");
        assert_eq!(dumps(&json!(i64::MIN)), "-9223372036854775808");
        // 1.0 is a float and must not collapse to "1".
        assert_eq!(dumps(&json!(1.0)), "1.0");
    }

    #[test]
    fn string_escaping_matches_python() {
        let v = json!("h\u{e9}llo \"q\" \\ \n \t \r \u{8} \u{c} \u{1} \u{1f} \u{7f} \u{2028} 🎨");
        assert_eq!(
            dumps(&v),
            "\"héllo \\\"q\\\" \\\\ \\n \\t \\r \\b \\f \\u0001 \\u001f \u{7f} \u{2028} 🎨\""
        );
    }

    #[test]
    fn layout_matches_python_indent2() {
        let v = json!({"b": [1, {"x": []}], "a": {}, "É": null});
        // Python: sorted keys are 'a' < 'b' < 'É' (code point order).
        assert_eq!(
            dumps(&v),
            "{\n  \"a\": {},\n  \"b\": [\n    1,\n    {\n      \"x\": []\n    }\n  ],\n  \"É\": null\n}"
        );
    }

    /// Documented divergence from Python: serde_json parses the integer
    /// literal `-0` as the float -0.0 (Python emits `0`). This pins the Rust
    /// behavior as spec — the token never occurs in Penpot exports.
    #[test]
    fn minus_zero_integer_literal_is_rust_spec() {
        let v: Value = serde_json::from_str("-0").unwrap();
        assert_eq!(dumps(&v), "-0.0");
    }

    /// Documented divergence: integers beyond u64/i64 are parsed lossily as
    /// f64 (Python keeps arbitrary precision). Never occurs in real exports.
    #[test]
    fn huge_integer_literal_is_rust_spec() {
        let v: Value = serde_json::from_str("123456789012345678901234567890").unwrap();
        assert_eq!(dumps(&v), "1.2345678901234568e+29");
    }

    /// Documented divergence: Python json accepts NaN/Infinity tokens and
    /// overflow-to-inf literals; Rust rejects them (safer for a sync engine).
    #[test]
    fn nonfinite_tokens_rejected() {
        assert!(serde_json::from_str::<Value>("NaN").is_err());
        assert!(serde_json::from_str::<Value>("Infinity").is_err());
        assert!(serde_json::from_str::<Value>("1e999").is_err());
    }

    #[test]
    fn duplicate_keys_last_wins_like_python() {
        let v: Value = serde_json::from_str(r#"{"a": 1, "a": 2}"#).unwrap();
        assert_eq!(dumps(&v), "{\n  \"a\": 2\n}");
    }
}
